### ISSUE TITLE
xlwing addin excel not working

### ISSUE THREAD

**Issue by fkalpa** [fkalpa/xlwings-Excel-addin#1]
---

trying to replicate the example on
https://www.youtube.com/watch?v=l_DgTxQ0aD8 

---

I installed python using Anaconda distribution 32 bit on Windows 7 Professional
I just upgraded to xlwings-0.7.2 using "$>pip install --upgrade xlwings". 

I created a folder in mydocs\PythonWings with 2 files: correl2.xlsm (similar 2D array like in video) and correl2.py (same code as in video). Once i hit the import Python UDFs button, I get "ImportError:Import by Filename is not supported" msgbox 

the code stops in VBA in the xlwings module in the "ImportPythonUDFs()" subroutine at the following line:
tempPath = Py.Str(Py.Call(Py.Module("xlwings"), "import_udfs", Py.Tuple(scriptPath, ThisWorkbook)))﻿

**Comment by fzumstein** [comment]
the idea was actually to create the issue on the xlwings repository: https://github.com/ZoomerAnalytics/xlwings/issues

**Comment by fkalpa** [comment]
issue has been posted to
https://github.com/ZoomerAnalytics/xlwings/issues/467
